module.exports =
    [
        "NONE",
        "BUTTON_DOWN",
        "BUTTON_UP",
        "ROTARY_LEFT",
        "ROTARY_RIGHT",
        "ADC_VALUES",
        "MENU_ITEMS",
        "KEYBOARD",
        "FREESOUND_SEARCH",
        "FREESOUND_PLAY",
        "FREESOUND_SEARCHRESULTS",
        "FREESOUND_PREV",
        "FREESOUND_NEXT",
        "RESULTS_PREV",
        "RESULTS_NEXT",
        "WAITING",
        "LOCAL_PLAY",
        "STOP_PLAYBACK"
    ];
